#include "type.h"

// Definir las instancias de tipos básicos
Type TYPE_NUMBER_INST = { TYPE_NUMBER, "number", NULL };
Type TYPE_STRING_INST = { TYPE_STRING, "string", NULL };
Type TYPE_BOOLEAN_INST = { TYPE_BOOLEAN, "boolean", NULL };
Type TYPE_VOID_INST = { TYPE_VOID, "void", NULL };
Type TYPE_UNKNOWN_INST = { TYPE_UNKNOWN, "unknown", NULL };
Type TYPE_ERROR_INST = { TYPE_ERROR, "error", NULL };

OperatorTypeRule operator_rules[] = {

// ----------------------  OPERATIONS ALLOWED  --------------------------------

//      left_type    |      right_type     |   return_type   | operator  

    // math binary
    { &TYPE_NUMBER_INST, &TYPE_NUMBER_INST, &TYPE_NUMBER_INST, OP_ADD },// +
    { &TYPE_NUMBER_INST, &TYPE_NUMBER_INST, &TYPE_NUMBER_INST, OP_SUB },// -
    { &TYPE_NUMBER_INST, &TYPE_NUMBER_INST, &TYPE_NUMBER_INST, OP_MUL },// *
    { &TYPE_NUMBER_INST, &TYPE_NUMBER_INST, &TYPE_NUMBER_INST, OP_DIV },// /
    { &TYPE_NUMBER_INST, &TYPE_NUMBER_INST, &TYPE_NUMBER_INST, OP_MOD },// %
    { &TYPE_NUMBER_INST, &TYPE_NUMBER_INST, &TYPE_NUMBER_INST, OP_POW },// ^
    //string binary
    { &TYPE_NUMBER_INST, &TYPE_STRING_INST, &TYPE_STRING_INST, OP_CONCAT},// @
    { &TYPE_STRING_INST, &TYPE_STRING_INST, &TYPE_STRING_INST, OP_CONCAT},
    { &TYPE_STRING_INST, &TYPE_NUMBER_INST, &TYPE_STRING_INST, OP_CONCAT},
    { &TYPE_NUMBER_INST, &TYPE_STRING_INST, &TYPE_STRING_INST, OP_DCONCAT},// @@
    { &TYPE_STRING_INST, &TYPE_STRING_INST, &TYPE_STRING_INST, OP_DCONCAT},
    { &TYPE_STRING_INST, &TYPE_NUMBER_INST, &TYPE_STRING_INST, OP_DCONCAT},
    //boolean binary
    { &TYPE_BOOLEAN_INST, &TYPE_BOOLEAN_INST, &TYPE_BOOLEAN_INST, OP_AND },// &
    { &TYPE_BOOLEAN_INST, &TYPE_BOOLEAN_INST, &TYPE_BOOLEAN_INST, OP_OR },// |
    //comparison
    { &TYPE_NUMBER_INST, &TYPE_NUMBER_INST, &TYPE_BOOLEAN_INST, OP_EQ },// ==
    { &TYPE_STRING_INST, &TYPE_STRING_INST, &TYPE_BOOLEAN_INST, OP_EQ },
    { &TYPE_BOOLEAN_INST, &TYPE_BOOLEAN_INST, &TYPE_BOOLEAN_INST, OP_EQ },
    { &TYPE_NUMBER_INST, &TYPE_NUMBER_INST, &TYPE_BOOLEAN_INST, OP_NEQ },// !=
    { &TYPE_STRING_INST, &TYPE_STRING_INST, &TYPE_BOOLEAN_INST, OP_NEQ },
    { &TYPE_BOOLEAN_INST, &TYPE_BOOLEAN_INST, &TYPE_BOOLEAN_INST, OP_NEQ },
    { &TYPE_NUMBER_INST, &TYPE_NUMBER_INST, &TYPE_BOOLEAN_INST, OP_GRE },// >=
    { &TYPE_STRING_INST, &TYPE_STRING_INST, &TYPE_BOOLEAN_INST, OP_GRE },
    { &TYPE_NUMBER_INST, &TYPE_NUMBER_INST, &TYPE_BOOLEAN_INST, OP_GR },// >
    { &TYPE_STRING_INST, &TYPE_STRING_INST, &TYPE_BOOLEAN_INST, OP_GR },
    { &TYPE_NUMBER_INST, &TYPE_NUMBER_INST, &TYPE_BOOLEAN_INST, OP_LSE },// <=
    { &TYPE_STRING_INST, &TYPE_STRING_INST, &TYPE_BOOLEAN_INST, OP_LSE },
    { &TYPE_NUMBER_INST, &TYPE_NUMBER_INST, &TYPE_BOOLEAN_INST, OP_LS },// <
    { &TYPE_STRING_INST, &TYPE_STRING_INST, &TYPE_BOOLEAN_INST, OP_LS },
    //unary
    { &TYPE_BOOLEAN_INST, NULL, &TYPE_BOOLEAN_INST, OP_NOT },// !
    { &TYPE_NUMBER_INST, NULL, &TYPE_NUMBER_INST, OP_NEGATE },// (-)
};

int rules_count = sizeof(operator_rules) / sizeof(OperatorTypeRule);